### ISSUE TITLE
confused on deployment

### ISSUE THREAD

**Issue by atsepkov** [ondreian/deliverance#2]
Hi,

Is this project still maintained? I'm trying to figure out how to deploy it. The installation instructions spawn a local server (which works but isn't integrated with Dokku), I assume to actually integrate it with Dokku I need to push it to an existing Dokku machine via 'git push' after adding Dokku as a remote? Or is there a config I should be editing instead to point to a Dokku server from wherever this server is running?

**Comment by atsepkov** [comment]
Nevermind, I seem to have gotten confused with what this UI was for, while looking at options for Dokku UI in github, the search + project description brought me to this project.

**Comment by ondreian** [comment]
Yeah, it isn't an actual UI for remote Dokku instances.

I have one of those in the works, but not enough free time right now to get it to the point to where I would feel comfortable with publishing it because it's kind of hacked together.  I'll ping this issue when I get around to polishing & publishing it.
